json.id feature.id
json.title feature.title
json.description feature.description
json.due_date feature.due_date
json.public feature.public
json.project_id feature.project_id
json.created feature.created_at
json.updated feature.updated_at
json.status feature.status
json.priority feature.priority
